### ISSUE TITLE
OpenEntityManagerInViewFilter by default

### ISSUE THREAD

**Issue by cpiciorus** [resthub/resthub-spring-stack#102]
Add 
servletContext.addFilter("Spring OpenEntityManagerInViewFilter", org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.class).addMappingForUrlPatterns(null, false, "/*"); 
to extend session duration

**Comment by sdeleuze** [comment]
Do we include OpenEntityManagerInViewFilter as default for JPA apps ?
Please provide arguments ...

**Comment by sdeleuze** [comment]
I think there s a consensus for not including this behaviour by default.
