### ISSUE TITLE
Throw exception in Http Client when the request return 4xx or 5xx status code

### ISSUE THREAD

**Issue by sdeleuze** [resthub/resthub-spring-stack#109]
I think this could be a good default behaviour.
Also, I think we should not throw checked exception since it make client painfull to use.

Any thoughts ?

**Comment by bclozel** [comment]
Good idea.
Should we implement only two of those?
- HTTPClientErrorException(HTTP status, HTTP message)
- HTTPServerErrorException(HTTP status, HTTP message)

Or should we try to have some specific Exception for common cases like forbidden, notfound...

**Comment by sdeleuze** [comment]
Not sure.
Perhaps we could reuse https://github.com/resthub/resthub-spring-stack/tree/master/resthub-web/resthub-web-server/src/main/java/org/resthub/web/exception by moving them to the resthub-web-common module ?

To be discussed ...

**Comment by bclozel** [comment]
opened issue #112 - moving exceptions to the resthub-web-common module.
I'll submit a pull request for the HTTP Client.
