### ISSUE TITLE
Non-wrapped array serialization support in Jackson?

### ISSUE THREAD

**Issue by bclozel** [resthub/resthub-spring-stack#110]
It looks like the issue is closed.

Should we enable this in RESThub and update documentation?

**Comment by sdeleuze** [comment]
Testing it is NOK for the moment -> https://github.com/FasterXML/jackson-dataformat-xml/issues/38

**Comment by sdeleuze** [comment]
As discussed in the previous Jackson link, Jackson 2.1 will not support root non-wrapped collection serialization, only property non-wrapped collection serialization.
