### ISSUE TITLE
NoClassDefFound jpa.EntityNotFoundException

### ISSUE THREAD

**Issue by bclozel** [resthub/resthub-spring-stack#126]
When trying out the mongodb archeytpes or running the todo-example application (with mvn jetty:run), I get the following exception.

It may be linked to issue #122 and its merged pull request.

**Comment by sdeleuze** [comment]
Ok I will rollback changes asked by Baptiste, it will fix this issue.

**Comment by sdeleuze** [comment]
Please review my pullrequest and close this issue if you are ok
