### ISSUE TITLE
Id in URL path for update method [server side]

### ISSUE THREAD

**Issue by dje-rom** [resthub/resthub-spring-stack#135]
Hello, 

I didn't understand why do we need to add the id of the object to update in the URL path (ServiceBasedRestController). It  add useless data inconsistency possibility between the real id in the ressource and the one in the path.

Assuming that it often technical id provided by DB (it will not changed on update) , it can be interresting to have a generic PUT method signature without it. What do you think about that ?

**Comment by bclozel** [comment]
I agree.

We define two kinds of REST services:
- "technical" REST services, for machine to machine communication; it is sometimes very useful to rely on a technical id.
- "sluggable" REST services, for general purposes; those services rely on a name, a slug, but not a technical Id for the reasons you listed. See [SluggableSampleServiceBasedRestController](https://github.com/resthub/resthub-spring-stack/blob/master/resthub-web/resthub-web-server/src/test/java/org/resthub/web/controller/SluggableSampleServiceBasedRestController.java)

**Comment by bclozel** [comment]
@dje-rom did my answer help you? Have I missed something?
