### ISSUE TITLE
Fix RepositoryBasedRestController and ServiceBasedRestController

### ISSUE THREAD

**Issue by sdeleuze** [resthub/resthub-spring-stack#148]
@code examples are broken, cf. http://resthub.org/javadoc/2.0/org/resthub/web/controller/ServiceBasedRestController.html

**Comment by bclozel** [comment]
because of [this](http://stackoverflow.com/questions/647195/how-do-you-escape-curly-braces-in-javadoc-inline-tags-such-as-the-code-tag).
This is so sad.

**Comment by bclozel** [comment]
it looks like `{@code }` can only be used for **inline code**.
