### ISSUE TITLE
Export less dependencies for contract modules

### ISSUE THREAD

**Issue by sdeleuze** [resthub/resthub-spring-stack#152]
Currently, when you write un myapp-contract module with only service interfaces + Pojo (model or DTO), you have to add a dependency to resthub-common. As a result, you get many unecessary dependencies like logback, cglib, etc.

Maybe we could create in RESThub 2.1 a resthub-contract module, remove dependency on Spring Data by creating wrappers for Page and Peageable interfaces.

**Comment by loicfrering** [comment]
We'll see later if we address this issue, closing for now.
