### ISSUE TITLE
Refactor archetypes to use WAR overlays

### ISSUE THREAD

**Issue by manosbatsis** [resthub/resthub-spring-stack#168]
Updating WAR modules when a new version of resthub (JS files etc) pops up can be error prone. Using overlays should allow editing/overriding of only specific resources while the rest are provided by a base WAR.

**Comment by sdeleuze** [comment]
Backbone JS WAR is already available from Maven Central, so feel free to use it. We have prefered to copy files in archetypes instead of using WAR overlays (we did that on RESThub 1.x) because it breaks JS and CSS validation in IDE.
