### ISSUE TITLE
Copy / Past error in resthub-web-client

### ISSUE THREAD

**Issue by Merguez22** [resthub/resthub-spring-stack#183]
Hi, 

i'm currently discovering your wonderfull Stack. I see an copy / past error,
headers must be replace by queryParameters !

public RequestHolder setQueryParameter(String name, String value) {
            if (queryParameters.containsKey(name)) {
                Collection<String> values = headers.get(name); <== here
                values.add(value);
            } else {
                List<String> values = new ArrayList<String>();
                values.add(value);
                queryParameters.put(name, values);
            }
            return this;
        }

**Comment by bclozel** [comment]
We're working on the 2.1.0 release - will fix this ASAP!
Thanks!
