### ISSUE TITLE
Fix BoneCP version

### ISSUE THREAD

**Issue by bmeurant** [resthub/resthub-spring-stack#193]
Current BoneCP version (0.8.0-rc1) seems lead to a really annoying bug : 

initial opened connections install locks and are started as "<IDLE> in transaction", causing multiple bugs and failure during database reindex and so on.

This bug is described here : https://bugs.launchpad.net/bonecp/+bug/1163856

-> **downgrading BoneCP version to last stable 0.7.1-RELEASE** fix this bug.

At the same time, we have to **update BoneCP configuration** :

Today initial pool size is set to 10 and max pool size to 50. At the same time, the number of partitions is set to 3 (that is correct for short transactions). But BoneCP initialize pool for each partition and this leads to an global initial pool size to 30 that is really huge.

We have to fix this and set default for min and max respectively to 2 and 4.

**Comment by sdeleuze** [comment]
Good catch !!!
