### ISSUE TITLE
Add domain driven Search support 

### ISSUE THREAD

**Issue by manosbatsis** [resthub/resthub-spring-stack#196]
I've implemented search for arbitrary entities for a 2tier and a 3tier stacks using Spring JPA Specifications and reflection to map HTTP search parameters to boolean, string, int, short, long, date, enum and many2one members extending org.springframework.data.domain.Persistable. I'm new to git but i should be able to patchup a pull request for 2.1 snapshot if you folks are interested.

**Comment by sdeleuze** [comment]
Nice, we are very interested. Could you send us a PR ?

**Comment by manosbatsis** [comment]
PR automatically opened #197 so I'm closing this one
