### ISSUE TITLE
Bug with asynchttpclient using SSL with proxies

### ISSUE THREAD

**Issue by matthieu-grigis** [resthub/resthub-spring-stack#199]
The 1.7.16 asynchttpclient raise some problems with SLL and proxies, the request doesn't use relative URI, even if the boolean UseRelativeURIsWithSSLProxies is set to true in the config Builder. Indeed in the constructor of AsyncHttpClientConfig, the attribute is passed but never set. To solve this issue you need to use 1.7.17 version and override AsyncHttpClientConfig constructor by adding this line : 
new line ->this.useRelativeURIsWithSSLProxies = useRelativeURIsWithSSLProxies;

you need also to override the function build from AsyncHttpClientConfig.Builder.
 public ClientConfig build() {
         new line -> return new ClientConfig

In attachment you will find my patch, to solve this issue : 
https://gist.github.com/matthieu-grigis/74013a5fa6e52f34317d

**Comment by bclozel** [comment]
Waiting for https://github.com/AsyncHttpClient/async-http-client/pull/330 to be resolved.

**Comment by sdeleuze** [comment]
Fixed, please test and make a feedback.
