### ISSUE TITLE
Adding swagger-springmvc cause NPE in PostInitializerRunner.java:42

### ISSUE THREAD

**Issue by aHenryJard** [resthub/resthub-spring-stack#214]
When I add https://github.com/martypitt/swagger-springmvc to my resthub projet (version 2.1.2), I have at tomcat startup this error:

java.lang.NullPointerException
        at org.resthub.common.util.PostInitializerRunner.onApplicationEvent(PostInitializerRunner.java:42)

I tried it on the TODO example application, and I get the same error at the test phase. To reproduce it with the todo example:

Add this dependency to the pom.xml

<dependency>
            <groupId>com.mangofactory</groupId>
            <artifactId>swagger-springmvc</artifactId>
            <version>0.6.2</version>
        </dependency>

Add some lines to the application context:

<context:property-placeholder location="classpath:swagger.properties" /> 
    <bean id="documentationConfig" class="com.mangofactory.swagger.configuration.DocumentationConfig"/>
    <bean id="extensibilityModule" class="com.mangofactory.swagger.configuration.ExtensibilityModule" />

And finnaly add swagger.properties to the project:

documentation.services.basePath=http://localhost:8080/
documentation.services.version=1.0

Then it crashes with a simple "mvn clean install".

**Comment by sdeleuze** [comment]
Fixed in 2.1.3-SNAPSHOT, and Todo example is now provided with Swagger by default, enjoy ;-)
