### ISSUE TITLE
Alternative to mvc:annotation-driven and params with dots improvements

### ISSUE THREAD

**Issue by bmeurant** [resthub/resthub-spring-stack#217]
## Alternative to mvc:annotation-driven

Last versions of Spring MVC provide a new way to override default behaviour related to request params with dots and extensions management.

The new configuration strongly depends on concrete project needs and a unique config cannot allow all possibilities.

Overriding this config necessitates to redefine _ContentNegotiationManager_ and/or _RequestMappingHandlerMapping_ that are defaultly defined by mvc:annotation-driven.

Since spring 3.2, mvc:annotation-driven allows to provide a custom _ContentNegotiationManager_ but in many cases, _RequestMappingHandlerMapping_ should also be defined to set a property and this cannot be done with mvc:annotation-driven.

For these reasons and in a general point of view, we need to provide a better way to end users to customize these behaviours and mvc:annotation-driven does not allow this : **we need to provide a complete configuration, miror of mvc-annotation-driven behaviour but easier to extend without redefining resthub key features such as Exception mapping**.

see : 
- https://jira.springsource.org/browse/SPR-6164
- https://jira.springsource.org/browse/SPR-7632
- http://stackoverflow.com/questions/11658353/spring-requestmapping-not-working-as-expected-if-there-are-extensions-in-url
- http://stackoverflow.com/questions/3693397/howto-get-rid-of-mvcannotation-driven
- http://stackoverflow.com/questions/16332092/spring-mvc-pathvariable-with-dot-is-getting-truncated
- http://stackoverflow.com/questions/3526523/spring-mvc-pathvariable-getting-truncated
- http://www.java-allandsundry.com/2013/01/spring-mvc-customizing.html

With such customization, users will be able to finely manage request params with dots : 

Consider a controller mapped on "/dot" with these two methods : 

``` java
@RequestMapping(method = RequestMethod.GET, value = "{param}")
    public @ResponseBody String getTest(@PathVariable String param) {
        return param;
    }

    @RequestMapping(method = RequestMethod.GET, value = "dot.{param}")
    public @ResponseBody String getDotTest(@PathVariable String param) {
        return param;
    }
```

The behaviour will be really different depending on the configuration :
## Default behaviour (no conf needed)

**conf** : no

**behaviour** :
- `/dot/noDot` will return `noDot`
- `/dot/noDot.json` will return `noDot`
- `/dot/noDot.xml` will return `noDot`
- `/dot/noDot.any` will return `noDot`
- `/dot/with.dot` will return `with`
- `/dot/with.dot.json` will return `with.dot`
- `/dot/with.dot.xml` will return `with.dot`
- `/dot/dot.included` will return `included`
- `/dot/dot.included.json` will return `included.json` !!
- `/dot/dot.included.xml` will return `included.xml` !!
## Disable suffixes detection

**conf** : `useSuffixPatternMatch=false`

``` xml
<bean id="handlerMapping"
          class="org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping">
        <property name="useSuffixPatternMatch" value="false"/>
    </bean>
```

**behaviour** :
- `/dot/noDot` will return `noDot`
- `/dot/noDot.json` will return `noDot.json`
- `/dot/noDot.xml` will return `noDot.xml`
- `/dot/noDot.any` will return `noDot.any`
- `/dot/with.dot` will return `with.dot`
- `/dot/with.dot.json` will return `with.dot.json`
- `/dot/with.dot.xml` will return `with.dot.xml`
- `/dot/dot.included` will return `included`
- `/dot/dot.included.json` will return `included.json`
- `/dot/dot.included.xml` will return `included.xml`
## Limit suffixes to registered ones

**conf** : `useRegisteredSuffixPatternMatch=true`

``` xml
<bean id="handlerMapping"
          class="org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping">
        <property name="contentNegotiationManager" ref="contentNegotiationManager"/>
        <property name="useRegisteredSuffixPatternMatch" value="true"/>
    </bean>

    <bean id="contentNegotiationManager" class="org.springframework.web.accept.ContentNegotiationManagerFactoryBean">
        <property name="favorPathExtension" value="false"/>
        <property name="favorParameter" value="true"/>
        <property name="mediaTypes">
            <value>
                json=application/json
                xml=application/xml
            </value>
        </property>
    </bean>
```

**behaviour** :
- `/dot/noDot` will return `noDot`
- `/dot/noDot.json` will return `noDot`
- `/dot/noDot.xml` will return `noDot`
- `/dot/noDot.any` will return `noDot.any`
- `/dot/with.dot` will return `with.dot`
- `/dot/with.dot.json` will return `with.dot`
- `/dot/with.dot.xml` will return `with.dot`
- `/dot/dot.included` will return `included`
- `/dot/dot.included.json` will return `included`
- `/dot/dot.included.xml` will return `included`

An alternative to mvc:annotation-driven will allow to implements the last two behaviours without redefining all resthub conf (not even explicitely defined today because of mvc automagic)

this issue is related to #188

**Comment by lhmoraes** [comment]
That is amazing and something that I'm looking for my project. In my project, I need to know if in the request coming ".json", ".xml" and etc. So, what is the code to get it ?

Thanks
