### ISSUE TITLE
Take a look to spring-data-rest

### ISSUE THREAD

**Issue by bmeurant** [resthub/resthub-spring-stack#223]
take a look and see if we can switch

http://projects.spring.io/spring-data-rest/

**Comment by bmeurant** [comment]
Some really good ideas and techniques to take from spring-data-rest but cannot be used as is because controllers are auto generated via annotations on repositories and cannot be customized or enhanced.

**Comment by manosbatsis** [comment]
Perhaps resthub could provide base class implementations for the generated controllers to extend along with factory. The approach is similarly used  for spring-generated repositories. That would allow controllers with access to both resthub and spring-data-rest code.
