### ISSUE TITLE
Add extension point to provide custom jackson ObjectMapper modules

### ISSUE THREAD

**Issue by bmeurant** [resthub/resthub-spring-stack#238]
Today, there is no simple way to "inject" custom Serialization module into Jackson ObjectMapper in Resthub.

If we want to provide a custom module to globally serialize owned or third-party object in a Resthub base application, we have to work with BeanPostProcessors.

It could be interesting to allow addition of custom modules through Resthub & Jackson configuration

**Comment by bclozel** [comment]
Maybe this?
https://jira.springsource.org/browse/SPR-11040

**Comment by bmeurant** [comment]
It sounds good ... I will test soon ! thx for the pointer !

**Comment by jripault** [comment]
Would be nice to have this declaration

```
<bean class="org.springframework.http.converter.json.Jackson2ObjectMapperFactoryBean">
   <property name="modulesToInstall" ref="resthubModules"/>
 </bean>
```

resthubModules being the list of Jackson modules to add for Resthub. and having a sublist, added to resthubModules for custom modules (same MO as jpaProperties)

**Comment by bclozel** [comment]
Also, in Boot - any ObjectMapper bean is automatically registered; see: [HttpMessageConvertersAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/0b7eda89d47753c4152e54686e199090dc9fbc28/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/HttpMessageConvertersAutoConfiguration.java).
