### ISSUE TITLE
Java based configuration

### ISSUE THREAD

**Issue by loicfrering** [resthub/resthub-spring-stack#25]
Promote and support Java based configuration with Spring. Java is a strong-typed language, get advantage of that!

Configurations will be simpler, shorter and testable.

**Comment by sdeleuze** [comment]
Ok for WebappInitializer (replace web.xml)

Spring 3.1.1 used in RESThub 2.0-beta1 allow users to use Java based configuration.

We will use Java based configuration as a default in archetypes when Spring Data will allow to scan repositories based on Java configuration.
