### ISSUE TITLE
Take advantage of Spring 3.1 profiles

### ISSUE THREAD

**Issue by loicfrering** [resthub/resthub-spring-stack#30]
Think of different profiles for different persistence technologies:
- data-jpa
- data-jpa-pgsql
- data-jpa-mysql
- data-jpa-h2
- data-mongodb
- data-graph

A profile should ne available to enable RESThub caching facilities.

Another one to enable monitoring thanks to JMX.

**Comment by jvillanti** [comment]
Split issue into two issues :
- this issue for "dynamic elements" (like JMX activation, cache, ...) with Spring 3.1 profiles
- second issue for the choice of tecnologies (like JPA/MongoDB, etc.) (see #43)

**Comment by sdeleuze** [comment]
I am in favor of using this before 2.0 release in order to replace 

<import resource="classpath*:resthubJpaContext.xml" />
<import resource="classpath*:resthubWebServerContext.xml" />

by jpa and webserver profiles ...
