### ISSUE TITLE
async REST client in RESThub

### ISSUE THREAD

**Issue by bclozel** [resthub/resthub-spring-stack#39]
- use jersey ahc client in RESThub framework([available in jersey contribs](http://java.net/projects/jersey/sources/svn/show/trunk/jersey/contribs/jersey-non-blocking-client))  
- refactor RESThub's client factory
- promote async usage & code style with documentation and examples

**Comment by bclozel** [comment]
same thing but with [async-http-client](https://github.com/sonatype/async-http-client).

**Comment by sdeleuze** [comment]
Initial support commited on resthub2 branch, to be improved

**Comment by sdeleuze** [comment]
Implemented in RESThub 2
