### ISSUE TITLE
Replace com.sun...JPEGEncoder by javax...imageio in roundtable app

### ISSUE THREAD

**Issue by bclozel** [resthub/resthub-spring-stack#42]
The package `com.sun.image.codec.jpeg` has been removed [in java7](http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6527962).

Roundtable app should be updated to use javax.imageio.
see `org.resthub.roundtable.toolkit.ImageTools` class.

**Comment by sdeleuze** [comment]
Fixed by removing this example in RESThub 2 ;-)
