### ISSUE TITLE
Compatibilty issues with jdk7

### ISSUE THREAD

**Issue by cuberri** [resthub/resthub-spring-stack#73]
The roundtable module compilation fails due to some missing package using jdk7.
The non-standard package com.sun.image.jpeg.codec has been removed from java7. Usage of ImageIO api is suggested.
http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6527962

**Comment by sdeleuze** [comment]
Fixed by removing this example from 2.0 ;-)
