### ISSUE TITLE
Multiple persistence units support

### ISSUE THREAD

**Issue by loicfrering** [resthub/resthub-spring-stack#9]
Support Spring 3.0.6 as soon as it is available. An important issue with multiple persistence units in Spring project is gonna be resolved: see [this issue](https://jira.springsource.org/browse/SPR-8594) in Spring Framework's JIRA.

**Comment by loicfrering** [comment]
The issue has been fixed and Spring 3.0.6 released. Unfortunately there is a new issue in Spring 3.0.6 (regression) which break completely RESThub.

We are now waiting for this new issue to be fixed, see [related issue](https://jira.springsource.org/browse/SPR-8660) in Spring Framework's JIRA.

Postponed to 1.1.3.

**Comment by loicfrering** [comment]
The BridgedMethod issue has now been corrected. Update Spring to 3.0.7 and 3.1.0-RC1 for RESThub2 related branches as soon as these releases are available.

**Comment by sdeleuze** [comment]
Fixed in RESThub 2
