### ISSUE TITLE
map IllegallArgumentException to Bad request

### ISSUE THREAD

**Issue by bmeurant** [resthub/resthub-spring-stack#99]
IllegallArgumentException currently leads to a `500 Internal Server Error`. Should be bound to a `400 Bad Request`

**Comment by loicfrering** [comment]
See:
- [JsonRepositoryBasedRestControllerTest.java#L71](https://github.com/resthub/resthub-spring-stack/blob/99cf9f7299f7650c6c8758c019f83bed4687c8bc/resthub-web/resthub-web-server/src/test/java/org/resthub/web/controller/JsonRepositoryBasedRestControllerTest.java#L71)
- [JsonServiceBasedRestControllerTest.java#L73](https://github.com/resthub/resthub-spring-stack/blob/99cf9f7299f7650c6c8758c019f83bed4687c8bc/resthub-web/resthub-web-server/src/test/java/org/resthub/web/controller/JsonServiceBasedRestControllerTest.java#L73)
- [XmlRepositoryBasedRestControllerWebTest.java#L74](https://github.com/resthub/resthub-spring-stack/blob/99cf9f7299f7650c6c8758c019f83bed4687c8bc/resthub-web/resthub-web-server/src/test/java/org/resthub/web/controller/XmlRepositoryBasedRestControllerWebTest.java#L74)
- [XmlServiceBasedRestControllerWebTest.java#L74](https://github.com/resthub/resthub-spring-stack/blob/99cf9f7299f7650c6c8758c019f83bed4687c8bc/resthub-web/resthub-web-server/src/test/java/org/resthub/web/controller/XmlServiceBasedRestControllerWebTest.java#L74)

**Comment by sdeleuze** [comment]
Fixed
